SELECT 
-- FROM RAW ORDERS
    O.ORDERID
    ,O.ORDERDATE
    ,O.SHIPDATE
    ,O.SHIPMODE
    ,O.ORDERSELLINGPRICE
    ,O.ORDERCOSTPRICE
    ,O.CUSTOMERID AS ORDER_CUSTOMER_ID
--CUSTOMERS
    ,C.*
-- FROM PRODUCT
    ,P.*
    ,(O.ORDERSELLINGPRICE - O.ORDERCOSTPRICE) AS ORDER_PROFIT

FROM {{ ref('RAW_ORDERS') }} AS O
LEFT JOIN 
     {{ ref('RAW_CUSTOMER') }} AS C
ON 
    C.CUSTOMERID = O.CUSTOMERID
LEFT JOIN
     {{ ref('RAW_PRODUCT') }} AS P
ON 
    P.PRODUCTID = O.PRODUCTID

